name: Push into main branch

on:
  push:
    branches:
      - main

env:
  GOTOOLCHAIN: local

jobs:
  # Asume that all tests passed during pull request phase
  test:
    name: Root tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Check code
        uses: actions/checkout@v4
        run: go test -v

  docker_build_push:
    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: qa
    name: Build docker image and push into registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image tag
        run: |
          export COMMITS=$(git rev-list --count HEAD)
          export COMMIT_SHA=$(git rev-parse --short HEAD)
          export TIMESTAMP=$(date +%s)
          export IMAGE_TAG="${COMMITS}-${COMMIT_SHA}-${TIMESTAMP}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        env:
          IMAGE_NAME: poc-hello
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_PREFIX }}-${{ env.IMAGE_TAG }}
