name: Push into feature branch

on:
  push:
    branches:
      - 'feat/**'

env:
  REGION: us-east1
  REGISTRY: us-east1-docker.pkg.dev
  REPOSITORY: poc
  IMAGE_BASE_NAME: hello

jobs:
  build_push_deploy:
    name: Build, Push, and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
       
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get branch name. Used later to build image and service names
      - uses: nelonoel/branch-name@v1.0.1

      # Using some data from github repo, build the docker image name (and tag)
      # Also, build Cloud Run service name
      # Put both names in the Action environment
      - name: Set up Docker image name and Cloud Run service name
        run: |
          IMAGE_TAG_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | cut -c1-50)
          COMMIT_NUMBER=$(git rev-list --count HEAD)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG_SUFFIX="${COMMIT_NUMBER}-${COMMIT_SHA}"

          echo "SERVICE_NAME=${{ env.IMAGE_BASE_NAME }}-${IMAGE_TAG_BRANCH}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_BASE_NAME }}:${IMAGE_TAG_BRANCH}-${IMAGE_TAG_SUFFIX}" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      # Deploy the created image to Cloud Run
      - name: Deploy into Google Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: ${{ env.REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.IMAGE_NAME }}
          flags: '--allow-unauthenticated'

      - name: Show Cloud Run URL
        run: |
          echo "URL: ${{ steps.deploy.outputs.url }}"
